### ISSUE TITLE
[BUG] <description>

### ISSUE THREAD

**Issue by kasinadhsarma** [VishwamAI/jobcity#61]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The actions at https://github.com/VishwamAI/jobcity/actions/runs/[###########]/job/[###########]?pr=60 are failing. Please investigate and fix the workflow so that the actions pass.

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Do you want to work on this issue?

No

**Comment by kasinadhsarma** [comment]
2s
Run npm run lint

> frontend@0.[1](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:1).0 lint
> eslint 'src/**/*.{js,jsx,ts,tsx}'


Oops! Something went wrong! :(

ESLint: 8.57.1

ReferenceError: Error while loading rule '@typescript-eslint/ban-ts-comment': structuredClone is not defined
Occurred while linting /home/runner/work/jobcity/jobcity/frontend/src/App.test.tsx
    at applyDefault (/home/runner/work/jobcity/jobcity/frontend/node_modules/@typescript-eslint/utils/dist/eslint-utils/applyDefault.js:1[4](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:5):21)
    at Object.create (/home/runner/work/jobcity/jobcity/frontend/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:30:72)
    at createRuleListeners (/home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:89[5](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:6):21)
    at /home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:10[6](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:7)6:110
    at Array.forEach (<anonymous>)
    at runRules (/home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:1003:34)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:1[7](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:8)30:31)
    at Linter._verifyWithFlatConfigArray (/home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:1[8](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:9)61:21)
    at Linter.verify (/home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:1433:65)
    at Linter.verifyAndFix (/home/runner/work/jobcity/jobcity/frontend/node_modules/eslint/lib/linter/linter.js:2068:2[9](https://github.com/VishwamAI/jobcity/actions/runs/11418242848/job/31771454483?pr=62#step:7:10))
Error: Process completed with exit code 2. lint issues at frontend part

**Comment by kasinadhsarma** [comment]
Run npm run lint

> frontend@0.1.0 lint
> eslint 'src/**/*.{js,jsx,ts,tsx}'


/home/runner/work/jobcity/jobcity/frontend/src/App.test.tsx
Error:   5:1  error  'test' is not defined    no-undef
Error:   8:3  error  'expect' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/App.tsx
Error:   17:19  error  'setTimeout' is not defined    no-undef
Error:   21:18  error  'clearTimeout' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/Dashboard.tsx
Error:   18:5  error  'document' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/auth-page.tsx
Error:   35:7  error  'console' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/Dashboard.tsx
Error:    [4](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:5):41  error  'Tooltip' is defined but never used             @typescript-eslint/no-unused-vars
Error:   29:10  error  'activeTab' is assigned a value but never used  @typescript-eslint/no-unused-vars

/home/runner/work/jobcity/jobcity/frontend/src/components/ErrorBoundary.tsx
Error:   22:[5](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:6)  error  'console' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ScrollToTopButton.tsx
Error:    7:9   error  'window' is not defined    no-undef
Error:   15:5   error  'window' is not defined    no-undef
Error:   22:5   error  'window' is not defined    no-undef
Error:   24:7   error  'window' is not defined    no-undef
Error:   [6](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:7)8:20  error  'document' is not defined  no-undef
Error:   [7](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:8)1:1   error  'document' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/avatar.tsx
Error:   9:33  error  'HTMLSpanElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/badge.tsx
Error:   4:32  error  'HTMLDivElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/button.tsx
Error:   37:3[8](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:9)  error  'HTMLButtonElement' is not defined  no-undef
Error:   42:33  error  'HTMLButtonElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/card.tsx
Error:    6:3   error  'HTMLDivElement' is not defined        no-undef
Error:    7:24  error  'HTMLDivElement' is not defined        no-undef
Error:   21:3   error  'HTMLDivElement' is not defined        no-undef
Error:   22:24  error  'HTMLDivElement' is not defined        no-undef
Error:   33:3   error  'HTMLParagraphElement' is not defined  no-undef
Error:   34:24  error  'HTMLHeadingElement' is not defined    no-undef
Error:   48:3   error  'HTMLParagraphElement' is not defined  no-undef
Error:   4[9](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:10):24  error  'HTMLParagraphElement' is not defined  no-undef
Error:   60:3   error  'HTMLDivElement' is not defined        no-undef
Error:   61:24  error  'HTMLDivElement' is not defined        no-undef
Error:   68:3   error  'HTMLDivElement' is not defined        no-undef
Error:   69:24  error  'HTMLDivElement' is not defined        no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/input.tsx
Error:   4:32  error  'HTMLInputElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/progress.tsx
Error:   4:35  error  'HTMLDivElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/switch.tsx
Error:   9:6  error  'className' is missing in props validation  react/prop-types

/home/runner/work/jobcity/jobcity/frontend/src/components/ui/tooltip.tsx
Error:   19:41  error  'HTMLElement' is not defined  no-undef
Error:   19:75  error  'HTMLElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/enhanced-job-city-ui.tsx
Error:    5:54  error  'Search' is defined but never used            @typescript-eslint/no-unused-vars
Error:    8:9   error  'React' is not defined                        no-undef
Error:    8:29  error  'React' is not defined                        no-undef
Error:    8:44  error  'SVGSVGElement' is not defined                no-undef
Error:   13:20  error  'React' is not defined                        no-undef
Error:   13:52  error  'icon' is missing in props validation         react/prop-types
Error:   13:64  error  'title' is missing in props validation        react/prop-types
Error:   13:71  error  'description' is missing in props validation  react/prop-types
Error:   29:9   error  'React' is not defined                        no-undef
Error:   29:29  error  'React' is not defined                        no-undef
Error:   29:44  error  'SVGSVGElement' is not defined                no-undef
Error:   32:21  error  'React' is not defined                        no-undef
Error:   32:54  error  'title' is missing in props validation        react/prop-types
Error:   32:61  error  'description' is missing in props validation  react/prop-types
Error:   32:74  error  'icon' is missing in props validation         react/prop-types

/home/runner/work/jobcity/jobcity/frontend/src/index.tsx
Error:   8:3   error  'document' is not defined     no-undef
Error:   8:38  error  'HTMLElement' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/jobcity.tsx
Error:    7:66   error  'React' is not defined  no-undef
Error:   20:[10](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:11)3  error  'React' is not defined  no-undef

/home/runner/work/jobcity/jobcity/frontend/src/landing-page.tsx
Error:    90:5   error  'document' is not defined           no-undef
Error:    92:7   error  'document' is not defined           no-undef
Error:    97:25  error  'HTMLAnchorElement' is not defined  no-undef
Error:   101:27  error  'document' is not defined           no-undef
Error:   106:9   error  'window' is not defined             no-undef
Error:   108:7   error  'window' is not defined             no-undef
Error:   159:33  error  'window' is not defined             no-undef
Error:   217:32  error  'alert' is not defined              no-undef

/home/runner/work/jobcity/jobcity/frontend/src/login-page.tsx
Error:   [11](https://github.com/VishwamAI/jobcity/actions/runs/11418278682/job/31771526653?pr=63#step:7:12):5   error  'console' is not defined                                         no-undef
Error:   79:16  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities

✖ 65 problems (65 errors, 0 warnings)

Error: Process completed with exit code 1.
